# Ficheiro: netlify.toml

[build]
  # Esta é a linha mais importante. Diz à Netlify para NÃO executar "npm install".
  command = "echo 'Build-less site, no command to run.'"
  
  # Publica os ficheiros da raiz do projeto.
  publish = "."

[functions]
  # Indica onde estão as suas funções de servidor.
  directory = "netlify/functions"
  
