# Ficheiro: netlify.toml

[build]
  # Executa o nosso novo script de build definido no package.json
  command = "npm run build"
  
  # Os ficheiros finais do site estarão na pasta "dist".
  publish = "dist"

[functions]
  # A localização das funções de servidor continua a mesma.
  directory = "netlify/functions"
  timeout = 25
