# Ficheiro: netlify.toml

[build]
  # Executa o nosso script de build definido no package.json
  command = "npm run build"
  
  # Os ficheiros finais do site estarão na pasta "dist".
  publish = "dist"

[functions]
  # Indica onde estão as suas funções de servidor.
  directory = "netlify/functions"

  # AUMENTA O TIMEOUT PARA 25 SEGUNDOS. Esta é a sintaxe correta.
  timeout = 25
